### ISSUE TITLE
ProgrammingError: can't adapt type 'HStoreDict'

### ISSUE THREAD

**Issue by yoanisgil** [djangonauts/django-hstore#143]
I'm running into a problem described by the title of this issue, and it's bugging me a bit because I cannot seem to find a proper explanation. Below my dependencies:

```
coverage (4.0.3)
Django (1.9)
django-filter (0.11.0)
django-hstore (1.4.1)
django-jenkins (0.18.1)
django-rest-swagger (0.3.4)
djangorestframework (3.3.2)
djangorestframework-gis (0.10)
djangorestframework-hstore (1.3)
funcsigs (0.4)
gunicorn (19.3.0)
mock (1.3.0)
pbr (1.8.1)
pep8 (1.6.2)
pip (7.1.2)
psycopg2 (2.6.1)
pyflakes (1.0.0)
PyJWT (1.4.0)
PyYAML (3.11)
requests (2.8.1)
rest-condition (1.0.2)
setuptools (18.2)
six (1.10.0)
stevedore (1.10.0)
virtualenv (13.1.2)
virtualenv-clone (0.2.6)
virtualenvwrapper (4.7.1)
wheel (0.24.0)
````

My *DATABASES* settings looks like this:

```python
DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': os.environ.get('DB_NAME', 'shovel'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST'),
        'PORT': os.environ.get('DB_PORT'),
    }
}
```

And the model looks like this:

```python
class Request(models.Model):
    objects = hstore.HStoreGeoManager()

    location_id = models.IntegerField()
    start_date = models.DateTimeField()
    priority = models.IntegerField(default=STANDARD_PRIORITY)
    location_properties = hstore.DictionaryField()
```

and this is what I get when I try to create a Request instance:

```python
>>>kwargs= {'priority': 1, 'location_properties': {}, 'location_id': 1, u'start_date': datetime.datetime(2016, 1, 18, 17, 15, 51, 664787)}
>>> models.Request.objects.create(**kwargs)
/srv/app/.virtualenvs/env/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py:1453: RuntimeWarning: DateTimeField Request.start_date received a naive datetime (2016-01-18 17:15:51.664787) while time zone support is active.
  RuntimeWarning)

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/srv/app/.virtualenvs/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/srv/app/.virtualenvs/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 401, in create
    obj.save(force_insert=True, using=self.db)
  File "/srv/app/.virtualenvs/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 700, in save
    force_update=force_update, update_fields=update_fields)
  File "/srv/app/.virtualenvs/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 728, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/srv/app/.virtualenvs/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 812, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/srv/app/.virtualenvs/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 851, in _do_insert
    using=using, raw=raw)
  File "/srv/app/.virtualenvs/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/srv/app/.virtualenvs/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 1039, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/srv/app/.virtualenvs/env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1064, in execute_sql
    cursor.execute(sql, params)
  File "/srv/app/.virtualenvs/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/srv/app/.virtualenvs/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/srv/app/.virtualenvs/env/local/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/srv/app/.virtualenvs/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: can't adapt type 'HStoreDict'
```

what I find strange is that I have a similar projet (same Django, PostgreSQL, django-hstore version) which uses django-hstore and it works like a charm. The main difference between those two is that the work that actually works does not use Postgis (but soon it  will need to). 

Any ideas?

**Comment by yoanisgil** [comment]
Closing this as i finally found the issue. I forgot to add 'django_hstore' to INSTALLED_APPS.
