### ISSUE TITLE
HSTORE adapter registration intermittently not applied

### ISSUE THREAD

**Issue by etianen** [djangonauts/django-hstore#47]
Every now and then, when one of my apps starts up after a period of inactivity, the HSTORE adapter fails to register, resulting in the following error traces:

```
Traceback (most recent call last):

 File "/home/ubuntu/webapps/guardian_advertising_jobs/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)

 File "/usr/local/lib/python2.7/dist-packages/newrelic-2.14.0.11/newrelic/hooks/framework_django.py", line 492, in wrapper
   return wrapped(*args, **kwargs)

 File "/home/ubuntu/webapps/guardian_advertising_jobs/venv/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
   return self.dispatch(request, *args, **kwargs)

 File "/home/ubuntu/webapps/guardian_advertising_jobs/guardian_advertising/apps/articles/views.py", line 110, in dispatch
   return super(AppMixin, self).dispatch(request, *args, **kwargs)

 File "/usr/local/lib/python2.7/dist-packages/newrelic-2.14.0.11/newrelic/hooks/framework_django.py", line 829, in wrapper
   return wrapped(*args, **kwargs)

 File "/home/ubuntu/webapps/guardian_advertising_jobs/venv/local/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
   return handler(request, *args, **kwargs)

 File "/home/ubuntu/webapps/guardian_advertising_jobs/guardian_advertising/apps/articles/views.py", line 198, in get
   return super(ArticleMixin, self).get(request, *args, **kwargs)

 File "/home/ubuntu/webapps/guardian_advertising_jobs/venv/local/lib/python2.7/site-packages/django/views/generic/detail.py", line 111, in get
   context = self.get_context_data(object=self.object)

 File "/home/ubuntu/webapps/guardian_advertising_jobs/guardian_advertising/apps/articles/views.py", line 256, in get_context_data
   context["title"] = unicode(self.object)

 File "/home/ubuntu/webapps/guardian_advertising_jobs/guardian_advertising/apps/articles/models.py", line 237, in __unicode__
   return unicode(self.content)

 File "/home/ubuntu/webapps/guardian_advertising_jobs/guardian_advertising/apps/articles/content/models.py", line 256, in __unicode__
   return self.title

 File "/home/ubuntu/webapps/guardian_advertising_jobs/guardian_advertising/apps/articles/content/fields.py", line 59, in __get__
   return self.value_from_instance(obj)

 File "/home/ubuntu/webapps/guardian_advertising_jobs/guardian_advertising/apps/articles/content/fields.py", line 42, in value_from_instance
   value = self.raw_value_from_instance(obj)

 File "/home/ubuntu/webapps/guardian_advertising_jobs/guardian_advertising/apps/articles/content/fields.py", line 35, in raw_value_from_instance
   return obj._article.fields.get(self.name, "")

AttributeError: 'str' object has no attribute 'get'
```

This also occurs in some background tasks, with the following trace:

```
Traceback (most recent call last):

 File "/home/ubuntu/webapps/guardian_advertising_jobs/guardian_advertising/apps/utils/tasks.py", line 43, in trigger_task
   signal.send(None, timestamp=timestamp)

 File "/home/ubuntu/webapps/guardian_advertising_jobs/venv/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 185, in send
   response = receiver(signal=self, sender=sender, **named)

 File "/home/ubuntu/webapps/guardian_advertising_jobs/venv/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
   return func(*args, **kwargs)

 File "/home/ubuntu/webapps/guardian_advertising_jobs/guardian_advertising/apps/utils/tasks.py", line 66, in do_site_refresh_task
   return func(timestamp)

 File "/home/ubuntu/webapps/guardian_advertising_jobs/guardian_advertising/apps/feeds/tasks.py", line 42, in import_twitter_accounts
   content = tweet_data["text"],

 File "/home/ubuntu/webapps/guardian_advertising_jobs/guardian_advertising/apps/feeds/models.py", line 37, in create_article
   defaults = defaults,

 File "/home/ubuntu/webapps/guardian_advertising_jobs/venv/local/lib/python2.7/site-packages/django/db/models/manager.py", line 154, in get_or_create
   return self.get_queryset().get_or_create(**kwargs)

 File "/home/ubuntu/webapps/guardian_advertising_jobs/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 391, in get_or_create
   six.reraise(*exc_info)

 File "/home/ubuntu/webapps/guardian_advertising_jobs/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 383, in get_or_create
   obj.save(force_insert=True, using=self.db)

 File "/home/ubuntu/webapps/guardian_advertising_jobs/venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
   force_update=force_update, update_fields=update_fields)

 File "/home/ubuntu/webapps/guardian_advertising_jobs/venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
   updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)

 File "/home/ubuntu/webapps/guardian_advertising_jobs/venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 654, in _save_table
   result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)

 File "/home/ubuntu/webapps/guardian_advertising_jobs/venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 687, in _do_insert
   using=using, raw=raw)

 File "/home/ubuntu/webapps/guardian_advertising_jobs/venv/local/lib/python2.7/site-packages/django/db/models/manager.py", line 232, in _insert
   return insert_query(self.model, objs, fields, **kwargs)

 File "/home/ubuntu/webapps/guardian_advertising_jobs/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 1514, in insert_query
   return query.get_compiler(using=using).execute_sql(return_id)

 File "/home/ubuntu/webapps/guardian_advertising_jobs/venv/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 903, in execute_sql
   cursor.execute(sql, params)

 File "/home/ubuntu/webapps/guardian_advertising_jobs/venv/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
   return self.cursor.execute(sql, params)

 File "/home/ubuntu/webapps/guardian_advertising_jobs/venv/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
   six.reraise(dj_exc_type, dj_exc_value, traceback)

 File "/home/ubuntu/webapps/guardian_advertising_jobs/venv/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
   return self.cursor.execute(sql, params)

 File "/usr/local/lib/python2.7/dist-packages/newrelic-2.14.0.11/newrelic/hooks/database_dbapi2.py", line 21, in execute
   return self.__wrapped__.execute(sql, parameters)

ProgrammingError: can't adapt type 'HStoreDict'
```

Libraries used by the site:

```
Django==1.6.5
Markdown==2.3.1
Pillow==2.3.0
South==0.8.4
astroid==1.0.1
beautifulsoup4==4.3.2
django-historylinks==1.0.3
django-hstore==1.2.3
django-pipeline==1.3.21
django-reversion==1.8.0
django-usertools==1.0.3
feedparser==5.1.3
futures==2.1.6
logilab-common==0.61.0
mock==1.0.1
psycopg2==2.5.2
python-dateutil==2.2
pytz==2013.9
six==1.5.2
uWSGI==2.0.1
wsgiref==0.1.2
```

Of most interest is the uWSGI library, which might (at a hunch), be doing something unexpected to the startup process (it's pre-forking). That's just a hunch, however.

**Comment by omkarvijay5** [comment]
upgrade django_hstore to 1.4
